var MongoClient = require("mongodb").MongoClient;
MongoClient.connect("mongodb://localhost/",function (err,db) {
  var myDb = db.db("words");
  myDb.createCollection("words_stats",function (err,words_stats) {
    addInsert(words_stats,{
      word:"idesadsdfsdfcsd",first:"i",last:"d",size:10,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"sdasdascavjkykm",first:"s",last:"m",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"erwdfbasdfcasd",first:"o",last:"o",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"vsdvasvfbfbdcsd",first:"i",last:"o",size:8,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"csvsvfdb",first:"a",last:"d",size:9,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"sdvsvsdvsdv",first:"p",last:"l",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"sdasdascavjkykm",first:"s",last:"m",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"vsdvs",first:"v",last:"m",size:6,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"cscdvvdfvas",first:"i",last:"o",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"csdvfbsfbv",first:"p",last:"m",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"svsdvsdvsdv",first:"s",last:"e",size:16,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"idesadsdfsdfcsd",first:"i",last:"d",size:10,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"sdasdascavjkykm",first:"s",last:"m",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"erwdfbasdfcasd",first:"s",last:"o",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"vsdvasvfbfbdcsd",first:"i",last:"o",size:8,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"csvsvfdb",first:"a",last:"d",size:9,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"sdvsvsdvsdv",first:"p",last:"l",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"sdasdascavjkykm",first:"s",last:"m",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"vsdvs",first:"v",last:"m",size:6,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"cscdvvdfvas",first:"i",last:"o",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"csdvfbsfbv",first:"p",last:"m",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"svsdvsdvsdv",first:"e",last:"e",size:16,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"idesadsdfsdfcsd",first:"i",last:"d",size:10,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"sdasdascavjkykm",first:"s",last:"m",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"erwdfbasdfcasd",first:"o",last:"o",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"vsdvasvfbfbdcsd",first:"i",last:"o",size:8,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"csvsvfdb",first:"a",last:"d",size:9,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"sdvsvsdvsdv",first:"p",last:"l",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"sdasdascavjkykm",first:"s",last:"m",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"vsdvs",first:"v",last:"m",size:6,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"cscdvvdfvas",first:"i",last:"o",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"csdvfbsfbv",first:"p",last:"m",size:14,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
    addInsert(words_stats,{
      word:"svsdvsdvsdv",first:"e",last:"e",size:16,letters:["i","d","f","s","t","s","f","x","fs"],stats:{"vowels":6,"consnants":3},charsets:{"type":"name","chars":"keke"}
    })
  })
});
function addInsert(collection,obj) {
  collection.insert(obj,function(err,results){
    if(!err){
      console.log(results);
    }
  })
}
